---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - ../../base/
  - strimzi-cluster-operator-0.43.0.yaml
  - apicurio-registry-operator-1.1.2-v2.5.11.final.yaml
  - cert-manager-v1.15.3.yaml

